create table UserConnection (
    userId varchar(255) not null,
    providerId varchar(255) not null,
    providerUserId varchar(255),
    rank int not null,
    displayName varchar(255),
    profileUrl varchar(512),
    imageUrl varchar(512),
    accessToken varchar(512) not null,
    secret varchar(512),
    refreshToken varchar(512),
    expireTime bigint,
    primary key (userId, providerId, providerUserId));
create unique index UserConnectionRank on UserConnection(userId, providerId, rank);



create table friend_list (
   id binary not null,
    user_id binary,
    primary key (id)
);
create table friend_list_friends (
   friend_list_entity_id binary not null,
    friends_id binary not null
);
create table role (
   id integer generated by default as identity,
    role varchar(255),
    primary key (id)
);

create table message (
    id binary not null,
    role varchar(255),
    from_user_id binary(255),
    to varchar(255),
    msg varchar(255),
    readed bit,
    primary key (id)
);

create table user (
    id binary not null,
    avatar_url varchar(255),
    email varchar(255),
    name varchar(255),
    password varchar(255),
    primary key (id)
);

create table user_roles (
    user_id binary not null,
    role_id integer not null,
    primary key (user_id, role_id)
);

alter table friend_list
   add constraint FK838n1nm0a7wvt1a9pxs0ft8kk
   foreign key (user_id)
   references user;

alter table message
   add constraint FK3nju8asf4v72h0d7g6vgtx7p2
   foreign key (from_user_id)
   references user;

alter table friend_list_friends
   add constraint FKcpyqangbh5kl18m7ewb7p0oug
   foreign key (friends_id)
   references user;

alter table friend_list_friends
   add constraint FK6dw7jces1ojfeq6wmvbj51guf
   foreign key (friend_list_entity_id)
   references friend_list;

alter table user_roles
   add constraint FKrhfovtciq1l558cw6udg0h0d3
   foreign key (role_id)
   references role;

alter table user_roles
   add constraint FK55itppkw3i07do3h7qoclqd4k
   foreign key (user_id)
   references user;